name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "CONNECTED TO EC2"

            # Fix PATH for non-interactive shell
            export PATH=/usr/bin:/usr/local/bin:$PATH

            node -v
            npm -v
            pm2 -v

            cd /home/ubuntu/ec2-test   # 👈 agar path alag ho to change karna

            git pull origin main
            npm install

            pm2 restart backend-app || pm2 start server.js --name backend-app

            pm2 save
